name: "S3 uploader"
description: "Upload a file or folder to an S3 bucket using the latest AWS client and the `s3 cp` command."
author: "a-sync"
runs:
  using: docker
  image: Dockerfile
branding:
  icon: upload-cloud
  color: blue
